#include "kanaria.h"

#include <algorithm>
#include <ctime>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {

bool expect(bool condition, const std::string& message)
{
    if (!condition) {
        std::cerr << message << '\n';
    }
    return condition;
}

bool has_candidate(const std::vector<kanaria::candidate>& candidates, const std::string& value)
{
    return std::any_of(candidates.begin(), candidates.end(), [&](const auto& item) {
        return item.candidate == value;
    });
}

std::vector<std::string> expected_date_candidates(int days)
{
    std::time_t now = std::time(nullptr);
    now += static_cast<std::time_t>(days) * 24 * 60 * 60;
    std::tm local {};
#if defined(_WIN32)
    localtime_s(&local, &now);
#else
    localtime_r(&now, &local);
#endif

    const int year = local.tm_year + 1900;
    const int month = local.tm_mon + 1;
    const int day = local.tm_mday;

    std::vector<std::string> out;
    out.push_back(std::to_string(year) + "年" + std::to_string(month) + "月"
                  + std::to_string(day) + "日");
    if (year >= 2019) {
        out.push_back("令和" + std::to_string(year - 2018) + "年"
                      + std::to_string(month) + "月" + std::to_string(day) + "日");
    }

    std::ostringstream dashed;
    dashed << std::setfill('0') << std::setw(4) << year << '-'
           << std::setw(2) << month << '-' << std::setw(2) << day;
    out.push_back(dashed.str());

    std::ostringstream slashed;
    slashed << std::setfill('0') << std::setw(4) << year << '/'
            << std::setw(2) << month << '/' << std::setw(2) << day;
    out.push_back(slashed.str());
    return out;
}

} // namespace

int main()
{
    auto engine = kanaria::engine_create();
    bool ok = true;

    const auto prediction2 = kanaria::engine_predict(*engine, "きょう", 2);
    ok &= expect(prediction2.size() == 2, "prediction limit 2 was not filled");

    const auto prediction5 = kanaria::engine_predict(*engine, "きょう", 5);
    ok &= expect(prediction5.size() == 5, "prediction limit 5 was not filled");

    const auto today = kanaria::engine_convert(*engine, "きょう", 20);
    ok &= expect(today.size() == 1, "default conversion returned sentence-level n-best results");
    ok &= expect(!today.empty() && today.front().candidate == "今日",
                 "dictionary candidate did not rank ahead of raw hiragana");
    ok &= expect(!today.empty()
                     && today.front().connection.left_id > 0
                     && today.front().connection.right_id > 0,
                 "candidate connection identifiers were not exposed");

    const std::string sentence = "きょうはいいてんき";
    const auto converted_sentence = kanaria::engine_convert(*engine, sentence, 20);
    ok &= expect(std::all_of(converted_sentence.begin(), converted_sentence.end(), [&](const auto& item) {
        return item.stroke == sentence;
    }), "clause fragments leaked into full-sentence candidates");
    const auto best_sentence = kanaria::engine_convert_best(*engine, sentence);
    ok &= expect(best_sentence && !best_sentence->elements.empty(),
                 "best sentence API did not expose its clause layout");

    const auto today_clauses = kanaria::engine_get_clause_candidates(*engine, "きょう", 0, 3, 100);
    ok &= expect(std::any_of(today_clauses.begin(), today_clauses.end(), [](const auto& item) {
        return item.candidate == "今日";
    }), "selected-clause enumeration omitted a dictionary candidate");
    ok &= expect(std::any_of(today_clauses.begin(), today_clauses.end(), [](const auto& item) {
        return item.candidate == "きょう";
    }), "autogenerated raw candidate did not participate in clause lookup");
    for (const auto& value : expected_date_candidates(0)) {
        ok &= expect(has_candidate(today_clauses, value),
                     "today date candidate was not generated: " + value);
    }

    const std::string abiko = kanaria::romaji_to_hiragana("abiko");
    const auto abiko_clauses = kanaria::engine_get_clause_candidates(*engine, abiko, 0, 3, 100);
    ok &= expect(has_candidate(abiko_clauses, "我孫子"),
                 "prediction dictionary entry was not merged into conversion candidates");

    const auto tomorrow_clauses = kanaria::engine_get_clause_candidates(*engine, "あした", 0, 3, 100);
    for (const auto& value : expected_date_candidates(1)) {
        ok &= expect(has_candidate(tomorrow_clauses, value),
                     "tomorrow date candidate was not generated: " + value);
    }

    const auto version_clauses = kanaria::engine_get_clause_candidates(*engine, "ばーじょん", 0, 5, 100);
    ok &= expect(has_candidate(version_clauses, "Kanaria-0.1"),
                 "version candidate was not generated");

    ok &= expect(kanaria::romaji_to_hiragana("zhzjzkzl") == "←↓↑→",
                 "Z+H/J/K/L romaji arrows were not generated");

    ok &= expect(kanaria::romaji_to_hiragana("TYA-TYU-TYO")
                     == kanaria::romaji_to_hiragana("cha-chu-cho"),
                 "tya/tyu/tyo romaji entries were not converted");

    const auto resized = kanaria::engine_resize_clause(*engine, sentence, 0, 3);
    ok &= expect(resized && !resized->elements.empty()
                     && resized->elements.front().value.stroke == "きょう",
                 "clause resize did not enforce the requested boundary");

    kanaria::word custom;
    custom.candidate = "カナリア";
    custom.stroke = "かなりあ";
    custom.frequency = 1000;
    custom.connection = today.front().connection;
    ok &= expect(kanaria::engine_add_user_word(*engine, custom), "user word was rejected");
    const auto custom_result = kanaria::engine_convert(*engine, custom.stroke, 1);
    ok &= expect(!custom_result.empty() && custom_result.front().candidate == custom.candidate,
                 "user word did not invalidate caches or enter conversion");
    ok &= expect(kanaria::engine_remove_user_word(*engine, custom), "user word was not removable");
    const auto removed_result = kanaria::engine_convert(*engine, custom.stroke, 1);
    ok &= expect(!removed_result.empty() && removed_result.front().candidate != custom.candidate,
                 "removed user word remained in a conversion cache");

    kanaria::candidate learned{ custom.candidate, custom.stroke, 700, custom.connection, 0 };
    ok &= expect(kanaria::engine_learn_candidate(*engine, learned, 10), "learning entry was rejected");
    const auto learned_result = kanaria::engine_convert(*engine, custom.stroke, 1);
    ok &= expect(!learned_result.empty() && learned_result.front().candidate == custom.candidate,
                 "learned word did not affect OpenWnn-style frequency selection");
    kanaria::engine_clear_learning(*engine);
    const auto cleared_result = kanaria::engine_convert(*engine, custom.stroke, 1);
    ok &= expect(!cleared_result.empty() && cleared_result.front().candidate != custom.candidate,
                 "cleared learning entry remained in a conversion cache");
    ok &= expect(kanaria::engine_add_user_word(*engine, custom), "reset test user word was rejected");
    kanaria::engine_reset(*engine);
    const auto reset_result = kanaria::engine_convert(*engine, custom.stroke, 1);
    ok &= expect(!reset_result.empty() && reset_result.front().candidate != custom.candidate,
                 "engine reset retained dictionary data or cached conversion results");

    const auto supplementary = kanaria::engine_convert(*engine, "😀", 5);
    ok &= expect(!supplementary.empty() && supplementary.back().candidate == "😀",
                 "supplementary Unicode character did not round-trip through UTF-16");

    std::string utf16_limit;
    for (int i = 0; i < 25; ++i) {
        utf16_limit += "😀";
    }
    ok &= expect(!kanaria::engine_convert(*engine, utf16_limit, 1).empty(),
                 "50-unit UTF-16 input was rejected");
    utf16_limit += "😀";
    ok &= expect(kanaria::engine_convert(*engine, utf16_limit, 1).empty(),
                 "UTF-16 input beyond the internal limit was accepted");

    return ok ? 0 : 1;
}
