#!/usr/bin/env python3
"""Generate WnnJpnDic.c from a generated binary blob TSV."""

from __future__ import annotations

import argparse
from collections import OrderedDict
from pathlib import Path


HEADER = """/*
 * Generated from a binary blob TSV. Do not edit this file directly.
 *
 * Copyright (C) 2008-2012  OMRON SOFTWARE Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0.
 */

#include <nj_lib.h>

"""


def read_tsv(path: Path) -> "OrderedDict[str, bytearray]":
    blobs: "OrderedDict[str, bytearray]" = OrderedDict()
    expected_sizes: dict[str, int] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split("\t")
        if len(parts) != 4:
            raise SystemExit(f"{path}:{lineno}: expected 4 tab-separated fields")
        record, name, field, payload = parts
        if record == "meta":
            if field != "size":
                raise SystemExit(f"{path}:{lineno}: unsupported meta field {field!r}")
            expected_sizes[name] = int(payload)
            blobs.setdefault(name, bytearray())
        elif record == "data":
            offset = int(field)
            values = bytes(int(x, 16) for x in payload.split()) if payload else b""
            blob = blobs.setdefault(name, bytearray())
            if len(blob) != offset:
                raise SystemExit(f"{path}:{lineno}: offset mismatch for {name}: got {offset}, expected {len(blob)}")
            blob.extend(values)
        else:
            raise SystemExit(f"{path}:{lineno}: unsupported record {record!r}")

    for name, size in expected_sizes.items():
        actual = len(blobs.get(name, b""))
        if actual != size:
            raise SystemExit(f"{path}: size mismatch for {name}: got {actual}, expected {size}")
    return blobs


def write_array(f, name: str, values: bytes) -> None:
    f.write(f"static uint8_t {name}[] = {{\n")
    for offset in range(0, len(values), 16):
        chunk = values[offset : offset + 16]
        f.write("\t\t")
        f.write(", ".join(f"0x{b:02x}" for b in chunk))
        f.write(",\n")
    f.write("};\n\n")


def write_c(blobs: "OrderedDict[str, bytearray]", output: Path) -> None:
    dic_names = [name for name in blobs if name.startswith("dic_")]
    con_names = [name for name in blobs if name.startswith("con_")]
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        for name, values in blobs.items():
            write_array(f, name, bytes(values))

        dic_slots = dic_names + ["NULL"] * max(0, 20 - len(dic_names))
        dic_sizes = [str(len(blobs[name])) for name in dic_names] + ["0"] * max(0, 20 - len(dic_names))
        dic_types = ["NJ_DIC_H_TYPE_NORMAL"] * 20

        f.write("uint8_t* dic_data[ ] = {\n")
        f.write("\t\t" + ", ".join(dic_slots) + "\n")
        f.write("};\n\n")

        f.write("uint8_t* con_data[ ] = {\n")
        f.write("\t\t" + ", ".join(con_names) + "\n")
        f.write("};\n\n")

        f.write("uint32_t dic_size[ ] = {\n")
        f.write("\t\t" + ", ".join(dic_sizes) + "\n")
        f.write("};\n\n")

        f.write("uint8_t dic_type[ ] = {\n")
        for item in dic_types:
            f.write(f"\t\t{item},\n")
        f.write("};\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("tsv", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    write_c(read_tsv(args.tsv), args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
