#!/usr/bin/env python3
"""Generate WnnJpnDic.c from human-readable dictionary TSV files.

The generated word dictionaries use OpenWnn's uncompressed custom dictionary
layout.  This keeps the source of truth in dict/*.tsv while still feeding the
existing C dictionary engine a native binary dictionary image.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path


NJ_DIC_IDENTIFIER = 0x4E4A4443
NJ_DIC_VERSION2 = 0x00020000
NJ_DIC_TYPE_CUSTOM_INCOMPRESS = 0x00020002
NJ_DIC_H_TYPE_NORMAL = 0x00
NJ_LEARN_DIC_HEADER_SIZE = 72
NJ_MAX_LEN = 50
NJ_MAX_RESULT_LEN = 50
NJ_MAX_CUSTOM_WORD_COUNT = 0xFFFF

POS_DATA_OFFSET = 0x20
POS_LEARN_WORD = 0x24
POS_MAX_WORD = 0x28
POS_QUE_SIZE = 0x2C
POS_NEXT_QUE = 0x30
POS_INDEX_OFFSET = 0x3C
POS_INDEX_OFFSET2 = 0x40

QUE_TYPE_JIRI = 1
QUE_TYPE_FZK = 2

INPUT_HEADER = [
    "stem_offset",
    "yomi",
    "candidate",
    "freq",
    "f_hinsi",
    "b_hinsi",
    "yomi_len",
    "candidate_len",
]

DICTIONARY_SLOTS = [
    ("prediction", QUE_TYPE_JIRI),
    ("prediction", QUE_TYPE_JIRI),
    ("uncompressed", QUE_TYPE_JIRI),
    ("suffix_words", QUE_TYPE_JIRI),
    ("single_kanji", QUE_TYPE_JIRI),
    ("independent_words", QUE_TYPE_JIRI),
    ("ancillary_words", QUE_TYPE_FZK),
]

FIXED_DICTIONARY_NAMES = {name for name, _ in DICTIONARY_SLOTS}

HEADER = """/*
 * Generated from dict/*.tsv. Do not edit this file directly.
 *
 * Copyright (C) 2008-2012  OMRON SOFTWARE Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0.
 */

#include <nj_lib.h>

"""


@dataclass(frozen=True)
class Entry:
    yomi: str
    candidate: str
    freq: int
    f_hinsi: int
    b_hinsi: int


def u32(value: int) -> bytes:
    return value.to_bytes(4, "little")


def u16(value: int) -> bytes:
    return value.to_bytes(2, "little")


def nj_chars(text: str) -> bytes:
    data = text.encode("utf-32-le")
    if len(data) > NJ_MAX_LEN * 4 and text:
        raise SystemExit(f"entry is too long for OpenWnn NJ_CHAR storage: {text!r}")
    return data


def read_entries(path: Path) -> list[Entry]:
    if not path.exists():
        return []

    out: list[Entry] = []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f, delimiter="\t")
        try:
            header = next(reader)
        except StopIteration:
            return []
        if header != INPUT_HEADER:
            raise SystemExit(f"{path}: unexpected header")
        for lineno, row in enumerate(reader, 2):
            if not row:
                continue
            if len(row) != len(INPUT_HEADER):
                raise SystemExit(f"{path}:{lineno}: expected {len(INPUT_HEADER)} columns")
            _, yomi, candidate, freq, f_hinsi, b_hinsi, _, _ = row
            if not yomi or not candidate:
                continue
            out.append(Entry(yomi, candidate, int(freq), int(f_hinsi), int(b_hinsi)))
    return out


def dictionary_name_for_extra(path: Path) -> str:
    stem = path.stem
    for name in sorted(FIXED_DICTIONARY_NAMES, key=len, reverse=True):
        if stem == name or stem.startswith(name + "_"):
            return name
    return "independent_words"


def read_grouped_entries(dict_dir: Path) -> dict[str, list[Entry]]:
    grouped = {name: [] for name in FIXED_DICTIONARY_NAMES}
    for path in sorted(dict_dir.glob("*.tsv")):
        name = dictionary_name_for_extra(path)
        grouped.setdefault(name, []).extend(read_entries(path))
    return grouped


def dedupe_entries(entries: list[Entry]) -> list[Entry]:
    best: dict[tuple[str, str, int, int], Entry] = {}
    for entry in entries:
        key = (entry.yomi, entry.candidate, entry.f_hinsi, entry.b_hinsi)
        known = best.get(key)
        if known is None or known.freq < entry.freq:
            best[key] = entry
    return list(best.values())


def build_word_dictionary(entries: list[Entry], que_type: int) -> bytes:
    entries = dedupe_entries(entries)
    entries.sort(key=lambda e: (e.freq, e.yomi, e.candidate, e.f_hinsi, e.b_hinsi))
    if len(entries) > NJ_MAX_CUSTOM_WORD_COUNT:
        entries = entries[-NJ_MAX_CUSTOM_WORD_COUNT:]

    encoded: list[tuple[Entry, bytes, bytes]] = []
    max_yomi_bytes = 4
    max_candidate_bytes = 4
    for entry in entries:
        yomi = nj_chars(entry.yomi)
        candidate = nj_chars(entry.candidate)
        max_yomi_bytes = max(max_yomi_bytes, len(yomi))
        max_candidate_bytes = max(max_candidate_bytes, len(candidate))
        encoded.append((entry, yomi, candidate))

    word_count = len(encoded)
    que_size = max(32, 5 + max_yomi_bytes + max_candidate_bytes)
    if que_size > 255:
        raise SystemExit(f"queue record size {que_size} exceeds OpenWnn's 8-bit copy path")

    index_offset = NJ_LEARN_DIC_HEADER_SIZE
    index_offset2 = index_offset + word_count * 2
    data_offset = index_offset2 + word_count * 2

    learn = bytearray(NJ_LEARN_DIC_HEADER_SIZE - 28)
    learn[POS_DATA_OFFSET - 28 : POS_DATA_OFFSET - 24] = u32(data_offset)
    learn[POS_LEARN_WORD - 28 : POS_LEARN_WORD - 24] = u32(word_count)
    learn[POS_MAX_WORD - 28 : POS_MAX_WORD - 24] = u32(word_count)
    learn[POS_QUE_SIZE - 28 : POS_QUE_SIZE - 24] = u32(que_size)
    learn[POS_NEXT_QUE - 28 : POS_NEXT_QUE - 24] = u32(0)
    learn[POS_INDEX_OFFSET - 28 : POS_INDEX_OFFSET - 24] = u32(index_offset)
    learn[POS_INDEX_OFFSET2 - 28 : POS_INDEX_OFFSET2 - 24] = u32(index_offset2)

    yomi_order = sorted(range(word_count), key=lambda i: (encoded[i][0].yomi, encoded[i][0].candidate))
    candidate_order = sorted(range(word_count), key=lambda i: (encoded[i][0].candidate, encoded[i][0].yomi))

    body = bytearray()
    body += learn
    for que_id in yomi_order:
        body += u16(que_id)
    for que_id in candidate_order:
        body += u16(que_id)

    for entry, yomi, candidate in encoded:
        if len(yomi) > 0x7F or len(candidate) > 0x7F:
            raise SystemExit(f"entry exceeds OpenWnn queue length field: {entry}")
        if entry.f_hinsi > 0x1FF or entry.b_hinsi > 0x1FF:
            raise SystemExit(f"part-of-speech id is too large: {entry}")

        record = bytearray(que_size)
        record[0] = que_type
        record[1:3] = u16((entry.f_hinsi << 7) | len(yomi))
        record[3:5] = u16((entry.b_hinsi << 7) | len(candidate))
        payload = yomi + candidate
        record[5 : 5 + len(payload)] = payload
        body += record

    footer = u32(NJ_DIC_IDENTIFIER)
    common = bytearray()
    common += u32(NJ_DIC_IDENTIFIER)
    common += u32(NJ_DIC_VERSION2)
    common += u32(NJ_DIC_TYPE_CUSTOM_INCOMPRESS)
    common += u32(len(body))
    common += u32(len(footer))
    common += u32(min(max_yomi_bytes, NJ_MAX_LEN * 4))
    common += u32(min(max_candidate_bytes, NJ_MAX_RESULT_LEN * 4))
    return bytes(common + body + footer)


def read_blob_tsv(path: Path) -> dict[str, bytes]:
    blobs: dict[str, bytearray] = {}
    expected: dict[str, int] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split("\t")
        if len(parts) != 4:
            raise SystemExit(f"{path}:{lineno}: expected 4 tab-separated fields")
        record, name, field, payload = parts
        if record == "meta":
            expected[name] = int(payload)
            blobs.setdefault(name, bytearray())
        elif record == "data":
            offset = int(field)
            blob = blobs.setdefault(name, bytearray())
            if len(blob) != offset:
                raise SystemExit(f"{path}:{lineno}: offset mismatch for {name}")
            blob.extend(int(x, 16) for x in payload.split())
        else:
            raise SystemExit(f"{path}:{lineno}: unsupported record {record!r}")
    for name, size in expected.items():
        actual = len(blobs.get(name, b""))
        if actual != size:
            raise SystemExit(f"{path}: size mismatch for {name}: got {actual}, expected {size}")
    return {name: bytes(value) for name, value in blobs.items()}


def write_array(f, name: str, values: bytes) -> None:
    f.write(f"static const uint8_t {name}[] = {{\n")
    for offset in range(0, len(values), 16):
        chunk = values[offset : offset + 16]
        f.write("\t\t")
        f.write(", ".join(f"0x{b:02x}" for b in chunk))
        f.write(",\n")
    f.write("};\n\n")


def write_c(output: Path, dictionaries: list[bytes], connections: dict[str, bytes]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        dic_names = []
        for i, values in enumerate(dictionaries, 1):
            name = f"dic_{i:02d}_data"
            dic_names.append(name)
            write_array(f, name, values)

        con_names = list(connections)
        for name, values in connections.items():
            write_array(f, name, values)

        dic_slots = dic_names + ["NULL"] * max(0, 20 - len(dic_names))
        dic_sizes = [str(len(values)) for values in dictionaries] + ["0"] * max(0, 20 - len(dictionaries))
        dic_types = ["NJ_DIC_H_TYPE_NORMAL"] * 20

        f.write("const uint8_t* const dic_data[ ] = {\n")
        f.write("\t\t" + ", ".join(dic_slots) + "\n")
        f.write("};\n\n")

        f.write("const uint8_t* const con_data[ ] = {\n")
        f.write("\t\t" + ", ".join(con_names) + "\n")
        f.write("};\n\n")

        f.write("const uint32_t dic_size[ ] = {\n")
        f.write("\t\t" + ", ".join(dic_sizes) + "\n")
        f.write("};\n\n")

        f.write("const uint8_t dic_type[ ] = {\n")
        for item in dic_types:
            f.write(f"\t\t{item},\n")
        f.write("};\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("dict_dir", type=Path)
    parser.add_argument("rule_blob_tsv", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    grouped_entries = read_grouped_entries(args.dict_dir)
    dictionaries: list[bytes] = []
    for name, que_type in DICTIONARY_SLOTS:
        entries = grouped_entries.get(name, [])
        dictionaries.append(build_word_dictionary(entries, que_type))

    connections = read_blob_tsv(args.rule_blob_tsv)
    write_c(args.output, dictionaries, connections)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
